### PR TITLE
WIP: Updated keepass dep to 0.3.3

### PR DESCRIPTION
**Pull request by caemor**
Updated mod.rs to be compatible with keepass 0.3.3 to make keepass-diff most likely non-unix compatible

Todo:
- error message in kdbx_to_sorted_vec (last map_err in there)
- in check_group directly iterate over the values of the two hashmaps?

### CODE REVIEW

**Comment by Narigo** [comment]
Hi @caemor thanks for the contribution. I'm trying to update the `keepass` dependency to version `0.3.3` after seeing your PR as I want to learn :)
I had trouble getting `cargo` to do anything as soon as I write `0.3.3` as version. It says:

> $ cargo build
> error: unable to get packages from source
> 
> Caused by:
>   failed to parse manifest at `/Users/joern/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-demangle-0.1.14/Cargo.toml`
> 
> Caused by:
>   feature `rename-dependency` is required
> 
> this Cargo does not support nightly features, but if you
> switch to nightly channel you can add
> `cargo-features = ["rename-dependency"]` to enable this feature

`cargo +nightly build` seems to get to the compile errors you probably fixed in your PR. But from the text, shouldn't there also be a line `cargo-features = ["rename-dependency"]` at the top of `Cargo.toml` to make users aware they need to use `cargo +nightly`?

Is it a good idea to use `cargo +nightly`?

**Comment by Narigo** [comment]
Actually, after upgrading Rust through `rustup update` and setting the version to `rustup default stable`, the error with `cargo-features = ["rename-dependency"]` went away... :) Will look into the breaking changes from `keepass` dependency..

**Comment by caemor** [comment]
This looks like I increased the minimum needed rust version with this PR because it is using a newer rust feature called "rename-dependency" which got added with version 1.31 (which got released at the end of 2018)

**Comment by Narigo** [comment]
@caemor I've updated to keepass 0.3.3 on a branch and tried to get the key file to run as well. I'm not very lucky in getting this to work right now. Maybe you could have a look at https://github.com/Narigo/keepass-diff/blob/update-keepass-dependency/src/diff/mod.rs#L57 and help me get the `key_file` from type `Option<&str>` to `Option<&mut std::io::Read>` correctly...? :)

**Comment by caemor** [comment]
The examples in here should help you: https://doc.rust-lang.org/std/io/trait.Read.html
The first one is using file::open(&str) to get the file.
But if you want to stay with copying the key_file into the terminal you could use the second example to convert the &str with the as_bytes() function which works because `Read from &str because &[u8] implements Read`

**Comment by Narigo** [comment]
The `key_file` being `Option<&str>` is just the path actually. So I've tried this implementation:
```
pub fn kdbx_to_sorted_vec(
  file: &str,
  password: Option<String>,
  key_file: Option<&str>,
) -> Result<SortedKdbxEntries> {
  let reader = match key_file {
    Some(file_name) => Some(&mut File::open(Path::new(file_name))?),
    None => None,
  };
  File::open(Path::new(file))
    .map_err(|e| Error::from(e))
    .and_then(|mut db_file| {
      Database::open(&mut db_file, password.as_ref().map(|s| s.as_str()), reader)
    })
    .map(|db: Database| accumulate_all_entries(db.root))
}
```

Which yields this error:
```
error[E0308]: mismatched types
  --> src/diff/mod.rs:58:75
   |
58 |       Database::open(&mut db_file, password.as_ref().map(|s| s.as_str()), reader)
   |                                                                           ^^^^^^ expected trait std::io::Read, found struct `std::fs::File`
   |
   = note: expected type `std::option::Option<&mut dyn std::io::Read>`
              found type `std::option::Option<&mut std::fs::File>`
```

I've also tried to create a reader like this, resulting in a borrow error:
```
pub fn kdbx_to_sorted_vec(
  file: &str,
  password: Option<String>,
  key_file: Option<&str>,
) -> Result<SortedKdbxEntries> {
  let reader: Option<&mut std::io::Read> = match key_file {
    Some(file_name) => {
      let f = &mut File::open(Path::new(file_name))?;
      Some(&mut f)
    }
    None => None,
  };
  File::open(Path::new(file))
    .map_err(|e| Error::from(e))
    .and_then(|mut db_file| {
      Database::open(&mut db_file, password.as_ref().map(|s| s.as_str()), reader)
    })
    .map(|db: Database| accumulate_all_entries(db.root))
}
```

The resulting compile errors:
```
error[E0597]: borrowed value does not live long enough
  --> src/diff/mod.rs:53:20
   |
53 |       let f = &mut File::open(Path::new(file_name))?;
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ temporary value does not live long enough
54 |       Some(&mut f)
55 |     }
   |     - temporary value dropped here while still borrowed
...
64 | }
   | - temporary value needs to live until here

error[E0597]: `f` does not live long enough
  --> src/diff/mod.rs:54:17
   |
54 |       Some(&mut f)
   |                 ^ borrowed value does not live long enough
55 |     }
   |     - `f` dropped here while still borrowed
...
64 | }
   | - borrowed value needs to live until here
```

Any idea what I need to change to get it working @caemor ?

**Comment by caemor** [comment]
You need a mix of your ideas.

The first one is just missing the &mut reader instead of reader and maybe an 'as dyn std::io::Read'
The second one is directly borrowing it, but the value that is borrowed only lives for as long as his own line.

there is an example here:
https://github.com/sseemayer/keepass-rs/blob/cfac2523aadca9ac4583354e13c13d54bb907435/tests/file_read_tests.rs#L45

I can't test it right now as I'm travelling, but if that still doesn't work. there is another possible way to use it with example here: https://github.com/sts10/medic/blob/e252fc2155203e66b3c5325f57f62e5347762505/src/lib.rs#L83

**Comment by Narigo** [comment]
I've tried the first link, when using the options `&str` value to map it to a `File`, the problem persists: . The second example worked, though, so I'm going to use this now.

Thanks a lot for your help! :)

**Pull request closed without merging**
