### PR TITLE
Update keepass dependency

### LINKED ISSUE #6: Provide --no-password-a / --no-password-b flags
With the update to keepass 0.3.3, keyfile authentication will be possible. If no passwords should be provided, it is not possible to say so via scripts right now.

Blocked by the upgrade to keepass 0.3.3.

- [x] Add `--no-password-a` flag
- [x] Add `--no-password-b` flag
- [x] Add `--no-passwords` flag

### PR DESCRIPTION
**Pull request by Narigo**
This should create the possibility to use files as keys.

The file from the keepass dependency works, but the tested files do not, yet. This should be investigated further (might be an issue with the dependency...)

Resolves #6

### CODE REVIEW

**Comment by Narigo** [comment]
I've added the `--no-passwords` / `--no-password-a` / `--no-password-b` flags in here as well.

Opening `kdbx` files with keys only works with the key file from the [upstream keepass repository / dependency](https://github.com/sseemayer/keepass-rs) for now. I'll merge this anyways and have to look into the key files again. Maybe @sseemayer can help here? 🙂

**Comment by sseemayer** [comment]
I'm traveling with only mobile phone access so please be aware that I am responding without reading the code underlying this commit or my own library code to any level of detail - apologies. Here are some possible reasons why this might not currently work for you:

If you wish to open a database with a keyfile and no password, be sure to use `None` for the password argument, not `Some("")`. AFAIR these two options will lead to different composite keys. 

There is currently an open issue that the newest version of the kdbx format is not supported yet. You might want to check the version of your database and if you get similar error messages.

For the sake of reproducibility, can you provide some dummy databases and keyfiles and the error messages that you are getting?

**Comment by Narigo** [comment]
@sseemayer thanks for taking your time to look at this! I'm pretty sure I'm using your library as intended: If I use the `kdbx` + `key` file from your keepass repository, it's working.

The problem is using my own key file that I've created through my KeePassX 2.0.3 client. You can find them [as `*_file.kdbx` and `keyfile.key` in the current pull request](https://github.com/Narigo/keepass-diff/tree/282470ad2d53b9db80044e3427a2a323f8d300ac/test).

Using my combination with the library only yields `Cryptography error` and will not open the file.

The main difference I can see is this: [Your `key` file](https://raw.githubusercontent.com/sseemayer/keepass-rs/0b84bc904491d02311a1c04581309edbc8c88f1e/tests/resources/test_key.key) is in binary format, showing binary data, while the one created by my Keypass client is [an XML file containing seemingly random data](https://raw.githubusercontent.com/Narigo/keepass-diff/282470ad2d53b9db80044e3427a2a323f8d300ac/test/keyfile.key).

Do you think it could be related to [the open issue about kdbx format 4 / Argon2](https://github.com/sseemayer/keepass-rs/issues/11)? I was under the impression that it does not have to do with using a file as key...

**Comment by sseemayer** [comment]
There are two keyfile styles containing either raw binary data or an XML file with the key base64 encoded, [both should be supported by the keepass crate](https://github.com/sseemayer/keepass-rs/blob/1daf12e89ae5412bd547943d95ab3cc06bbebb79/src/keyfile.rs#L41-L52). 

Thanks for sharing your example databases, I haven't made it back to my computer yet / had a chance to look into what is happening but would also guess that this might be related to the KDBX 4 format. I hope to find some time for it this weekend but cannot guarantee it yet.

**Comment by Narigo** [comment]
@sseemayer I'll open an issue on your repository for adding a test with an XML file, linking to the test databases I have here. Thanks for looking into this! :)

**Comment by sseemayer** [comment]
The Cryptography error means that something went wrong during some step of the key derivation process so that the derived master key cannot decrypt the database - this could be for many reasons unfortunately. 

I will work on KDBX4 this weekend but hope that we can get around to debugging this later.

**Comment by sseemayer** [comment]
Should be working again now :)

**Comment by Narigo** [comment]
Indeed, it does! Thanks a lot @sseemayer ! :)

**Pull request merged**
